-- Run in Supabase SQL Editor or Studio
create table mqtt_logs (
  id bigint generated by default as identity primary key,
  broker text not null,
  topic text not null,
  payload jsonb not null,
  created_at timestamptz default now()
);
