services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"     # plain MQTT (dev only - comment out in prod)
      - "8883:8883"     # MQTTS (secure MQTT)
      - "9001:9001"     # wss:// secure WebSockets
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro   # :ro = read-only
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ./certs:/mosquitto/config/certs:ro
      - ./passwd:/mosquitto/config/passwd:ro
    restart: unless-stopped