name: ESP32 CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up PlatformIO
      uses: platformio/platformio-action@v1
    - run: pio run
    - run: pio test -e unit_test
